### ISSUE TITLE
`kcli clone --base EXISTING_TEMPLATE_NAME NEW_VM_NAME` throws `ModuleNotFoundError: No module named 'cryptography'`

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#467]
Here's a picture of the err:

![image](https://user-images.githubusercontent.com/80959443/193598257-cebdc0ea-f854-4a4c-b413-7ff1efaf6509.png)

---

Is this "simply" because `kcli clone` is not supported on `vSphere` yet?

Thanks

**Comment by karmab** [comment]
fixed at https://github.com/karmab/kcli/commit/41570147db84f33dbd6f92024d1538a57a9efa80 by implementing cloning function

**Comment by LarsBingBong** [comment]
Hmm I still get errors like

![image](https://user-images.githubusercontent.com/80959443/193658584-a4f8099c-adc7-4ba8-ac30-b1dc3249ff43.png)

---

As you can see I tried installing the `cryptography` module. However, it wasn't enough. Not it's complaining of `pyVmomi`. I'm no `Python` expert. However, should it be up to the end-user to install required modules or the like before a prog. can work?
In this case `kcli`. Previously that was never the case. Using `kcli clone` is the first time I bump into that.

**Comment by LarsBingBong** [comment]
So I had some env. issues in regards to Python. Those are fixed now. So now we/I can actually test the `clone` feature when used towards a vSphere/VMWare HCI.

Thank you.
