### ISSUE TITLE
Sometimes still getting prompted on whether the temp ssh key should be overwritten

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#468]
See:

![image](https://user-images.githubusercontent.com/80959443/195307754-63fcf70b-0908-4c19-a15a-1d1a07d29d22.png)

Prompted today on kcli version `version: 99.0 commit: 8eeddd2 2022/10/03`. I don't see any updates to `ssh` key handling in the commits after.

Any ideas?

Thank you very much.

**Comment by karmab** [comment]
it is expected when you're deploying using threaded.
while it may seem misleading, the workflow works as expected

**Comment by LarsBingBong** [comment]
Exactly @karmab the question should automatically be answered by `kcli` so the end-user will never ever be prompted for this 👍🏿 

Thanks

**Comment by karmab** [comment]
let's see if https://github.com/karmab/kcli/commit/bda96d66c68f9a218ac5b6bc18e469e43bd04321 addresses it.
Reopen this issue if needed

**Comment by larssb** [comment]
Better ... I'm not prompted anymore. However, it looks a little "ugly" when `kcli` tries to do its thing. See:

<img width="685" alt="Screenshot 2022-10-18 at 20 06 16" src="https://user-images.githubusercontent.com/5261530/196509919-2f3d4bde-7c84-4fbf-a8ab-8b30d31cd5c2.png">

Put that in your pipe and smoke it :-) ...

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/ff392e5c41ffc212f88b1fffc63f3166ce15012a

**Comment by LarsBingBong** [comment]
Still seeing this and I think it's because of this > https://stackoverflow.com/a/46548181 - in some of our `Bash` scripts we set `set -o pipefail`

So maybe this `yes 2>/dev/null | ./MyScript.sh` is the most "beautiful" way of making `kcli` compatible with strict `Bash` mode?

What do you think?
