### ISSUE TITLE
Misleading warning output when running KCLI to scale worker node into a K3s based cluster.

### ISSUE THREAD

**Issue by larssb** [karmab/kcli#650]
## The issue at hand

So I'm seeing this:

<img width="1316" alt="Screenshot 2024-03-07 at 16 49 58" src="https://github.com/karmab/kcli/assets/5261530/e5c93ebb-d113-4fc5-a427-3d09c5cc7d90">

As this particular VM, to be a worker node on a K3s based cluster, is being deployed on GCP GCE and thereby the `keepalived` `control-plame VIP service` cannot be used - we're not using neither the `auth_pass` or the `virtual_router_id`.

More confusing is this warning:

<img width="1365" alt="Screenshot 2024-03-07 at 16 50 59" src="https://github.com/karmab/kcli/assets/5261530/ee234737-b886-4818-b987-73655c3a62c2">

The thing is that the `~/.ssh` certainly contains SSH keys. See:

<img width="1176" alt="Screenshot 2024-03-07 at 16 51 58" src="https://github.com/karmab/kcli/assets/5261530/02e7e995-b8f0-454a-8cc0-bebb8ce3659c">

So there should be no reason for `KCLI` to "complain" 👍 . I don't remember ever seeing this warning when **NOT** running inside a `container` >> in a `Pod` on `Kubernetes`.

Further, the SSH key was also properly attached on the VM on the Google Cloud Compute Engine SaaS offering.

<img width="1306" alt="Screenshot 2024-03-07 at 16 53 35" src="https://github.com/karmab/kcli/assets/5261530/fa636740-dc4f-4249-aea4-96da01c28be0">

---

## Further context

K3s version: v1.28.6
KCLI version: 1e6a0f1 2024/03/07
HCI platform in play: GCP GCE
The container image is based off of the KCLI base image. So: `FROM quay.io/karmab/kcli:latest`

---

Thank you very much.

**Comment by karmab** [comment]
I addressed the scale warning thing in a recent commit.
About the missing public key, it's indeed missing from your output (only the private key seems to be there).
In cloud platforms, that might be a wrong message since one can use project wide keys

**Comment by larssb** [comment]
Yes there's no longer any scale warning. The ssh key warning I still don't understand. As I show in one of the initial posts screenshots - there's indeed an SSH id_rsa key in the `~/.ssh`.

I'm using the `keys` key in the `KCLI parameter file`. 

Am I misunderstanding something here?

**Comment by karmab** [comment]
this commit https://github.com/karmab/kcli/commit/74312a32e6b947d6ab8a542dedfa9d0b75759756 will remove the warning when keys are provided

**Comment by larssb** [comment]
> this commit [74312a3](https://github.com/karmab/kcli/commit/74312a32e6b947d6ab8a542dedfa9d0b75759756) will remove the warning when keys are provided

I'll test it out soon. Thank you very munchies.
